### ISSUE TITLE
Agility Helper: Priff support

### ISSUE THREAD

**Issue by therealosrsramen** [Ganom/Supporter-Issue-Tracker#11]
**Is your feature request related to a problem? Please describe.**
Not related to any problems.
**Describe the solution you'd like**
Add Priffdinas(elf) agility course to A-H
**Describe alternatives you've considered**
Although the other courses are _somewhat_ close in terms of EHP, prif is actually the best rooftop course for xp.
Also being a somewhat less-used course, I'd gathered its less likely to be reported here compared to say; seers/rell/pollniveach.
**Additional context**

**Comment by Failed4life** [comment]
Priff agility course has been added in the open beta
