### ISSUE TITLE
Agility Helper: Brimhaven Agility Arena

### ISSUE THREAD

**Issue by xPauly** [Ganom/Supporter-Issue-Tracker#122]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Would be nice for the graceful recolor and the pirate's hook. Also it's not horrible xp/hr.

**Describe alternatives you've considered**
N/A

**Additional context**
https://oldschool.runescape.wiki/w/Brimhaven_Agility_Arena

**Comment by Ganom** [comment]
This would likely require its own plugin and its too niche of a scope.
