### ISSUE TITLE
Agility Helper: Ape Atoll agility course addition

### ISSUE THREAD

**Issue by bigrob6969** [Ganom/Supporter-Issue-Tracker#124]
**Is your feature request related to a problem? Please describe.**
No problem, just a feature request

**Describe the solution you'd like**
if we can have ape atoll agility course added to agility helper that'd be pogtits.

**Additional context**
not sure if its possible or would need a whole seperate plugin but itll be nice if we get it added

**Comment by Failed4life** [comment]
This is already a feature
