### ISSUE TITLE
RC Bot/Helper - Add Stamina Support

### ISSUE THREAD

**Issue by xBusse** [Ganom/Supporter-Issue-Tracker#129]
The RC process usually utilizes Stamina Potions, so it even feels unrealistic to not use them when doing things like running lavas.  The run energy depletes very quickly with full inventories of runes, even with full graceful (minus headgear), and heavily reduces the potential xp/hr.

I feel it would make sense to implement a Stamina Potion feature very similar to the Blast Furnace Helper, which drinks one does while in the bank. Thresholds can be set similar to the Agility Helper as well.

I know this has been talked about in Discord before, but I did not see any open issues.  Hopefully it's not something already being considered elsewhere.  Thanks for everything!

**Comment by Failed4life** [comment]
Rcbot already uses staminas
