### ISSUE TITLE
Advanced swapper: a:last inconsistent/not working on players

### ISSUE THREAD

**Issue by ZZNQX** [Ganom/Supporter-Issue-Tracker#14]
**Describe the bug**
a:last string not working on players

**To Reproduce**
1. Go to advanced swapper
2. add a:last string
3. try on player
4. doesnt work

**Expected behavior**
it should focus on the last targetted player

**Screenshots**

**Additional context**
a:cast works fine

**Comment by ZZNQX** [comment]
id like to add that the version from 21-05-2020 11:30 works perfectly

**Comment by Ganom** [comment]
The attack command from previous version was actually broke for everything besides players. The update split the indexing of both the last interacted npc and player. Currently the plugin is reacting to you interacting with another player, but for what ever reason its not being reliable as it should be. Next release will include both methods as an attempt to fix the issue.
