### ISSUE TITLE
Agility helper: Spam eating while unable to eat on Ardy course 

### ISSUE THREAD

**Issue by justanotherGHuser** [Ganom/Supporter-Issue-Tracker#15]
**Describe the bug**
While training on the Ardy course, when walking on any segments where your player is auto walked while you're can't interact, if your agility level dips below 90, the plugin will try to spam eat a pie.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to any spot on the Ardy agility course where you're auto walked by the game.
2.  Time it so your agility level drops below 90 while being auto walked.
3. See error.

**Expected behaviour**
Ideally, I'd like for it to wait till you finish the auto-walking section so that it doesn't behave so bot like.

**Comment by Ganom** [comment]
A simple animation check before eating should solve this.
