### ISSUE TITLE
Combat Helper - extended boost support

### ISSUE THREAD

**Issue by n1ckpvp** [Ganom/Supporter-Issue-Tracker#150]
**Is your feature request related to a problem? Please describe.**
Currently the Combat Helper's boost functionality is really limited. The only options currently implemented are Drink Range, Mage and Super Combat 1/0.

**Describe the solution you'd like**
Ideally, we should be able to select the potions/boost items we'd like to use and set the thresholds to repot ourselves. Imbued heart is better than mage pot in most situations, so it should be supported as well (might require additional support for the cooldown).

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ThatGamerBlue** [comment]
I've added a config option for the boost threshold, imbued heart timers are nigh-on impossible to program accurately however, so for now that's a wontfix.
