### ISSUE TITLE
Agility helper: Spam click marks when you have a full invent

### ISSUE THREAD

**Issue by justanotherGHuser** [Ganom/Supporter-Issue-Tracker#16]
**Describe the bug**
When training Agility on the Ardy course, if you have a full invent (pies) it will spam click the marks.

**To Reproduce**
1. Fill up inventory with pies and eat one to get a pie dish.
2. Train agility till we need to pick up a mark
3. See error

**Expected behavior**
Not spam click the mark ideally. Maybe drop empty pies or dishes/stop the plugin?

**Screenshots**

**Additional context**

**Comment by Ganom** [comment]
This should already have a check in it, but I'll make sure to take a look.
