### ISSUE TITLE
New Feature for Combat Helper

### ISSUE THREAD

**Issue by ambitiouss** [Ganom/Supporter-Issue-Tracker#161]
**Is your feature request related to a problem? Please describe.**
no, at least it shouldn't be.
**Describe the solution you'd like**
I would love to have Antipoison/antidote/antivenoms/super antifires to work with the combat helper plugin/ maybe also add reactivate imbued heart
**Describe alternatives you've considered**
NA
**Additional context**
NA

**Comment by ThatGamerBlue** [comment]
Imbued heart is notoriously difficult to track so that's a wontfix for now, but the antipoison/antifires will be in the next release.
