### ISSUE TITLE
Advanced Swapper Not toggling back on

### ISSUE THREAD

**Issue by Akram-Techs** [Ganom/Supporter-Issue-Tracker#166]
**Describe the bug**
Before when I toggled advanced swapper off to type I would be able to toggle it back on and immediately use the hotkeys/it work again. Now it just isn't toggling back on and working normally without a client restart or if a key gets reassigned. When i toggle the plugin on/off there is a 4 FPS drop as if its doing something. While writing this I tried more things to get it to work without reassigning a key or client restarting. I found out that if I switched in-between a profile within the plugin, as in saved gear switches, it would work as normal again.

**To Reproduce**
1. Go to Advanced Swapper and setup a gear switch 
2. After assigning a key to that gear switch go ahead and press that key to see that it is in fact working.
3. Go back to Advanced Swapper and disable the plugin and re-enable it.
4. Try the assigned key to the gear switch. (which should not work now)
5. Go into Advanced Swapper and select the gear switch which was previously setup and reassign the key to the same or a new one.
6. The gear switch should work now.

**Expected behavior**
When the plugin was toggled off a week or so ago i was able to toggle it back on and continue using it without having to reassign a key or restart my client.

**Additional context**
Client log attached

[client.log](https://github.com/Ganom/Supporter-Issue-Tracker/files/5863665/client.log)

Here is another client log after removing some plugins.

[client.log](https://github.com/Ganom/Supporter-Issue-Tracker/files/5863748/client.log)

**Comment by dlaw1990** [comment]
Can confirm. I've noticed same behaviour. Also, if you reassign a key with plugin disable, the plugin somehow is usable while it's disabled and works again @zudss

**Comment by dlaw1990** [comment]
+1 on request for a disable key

**Comment by Akram-Techs** [comment]
> Can confirm. I've noticed same behaviour. Also, if you reassign a key with plugin disable, the plugin somehow is usable while it's disabled and works again @zudss

I have noticed that as well. having to make sure i enable then disable to make sure its off or to turn it back on i need to reassign a key if you need to type often it gets annoying.
