### ISSUE TITLE
RCBot - "Cannot find ring of dueling" message when using Crafting cape for banking (mind runes)

### ISSUE THREAD

**Issue by sf0000** [Ganom/Supporter-Issue-Tracker#167]
**Is your feature request related to a problem? Please describe.**
The RCBot spams the "encountered a fail state" if you're using crafting cape. 

**Describe the solution you'd like**
Include the ability to toggle debug/error messages

**Describe alternatives you've considered**

**Additional context**

**Comment by Failed4life** [comment]
Can you provide additional information? A screenshot of the error and a copy of your client.log would be helpful

**Comment by sf0000** [comment]
![image](https://user-images.githubusercontent.com/77947137/105660765-bbcaba80-5f06-11eb-9ab5-861359ce3490.png)
[client.log](https://github.com/Ganom/Supporter-Issue-Tracker/files/5864142/client.log)

**Comment by Failed4life** [comment]
My first question was going to be which runes are you doing, but I can see you're doing mind runes. Do you have the crafting cape equipped?

**Comment by sf0000** [comment]
yup, it runs normally but just spams that message
