### ISSUE TITLE
Damage Threshold on Auto Spec 2 isn't working

### ISSUE THREAD

**Issue by joooooon** [Ganom/Supporter-Issue-Tracker#181]
Ive been using Auto Spec for quite some time - Just got plat again to continue using this great script and "Damage Threshold is not working". The rest of the script works besides that part. I've cleared all the other externals out of my plugins file and external manger, still doesn't work.

Would love to have this working again. Thank you!

**Comment by ThatGamerBlue** [comment]
Fixed in dev.

e: update pushed
