### ISSUE TITLE
Advanced Boss Swapper not working at Saradomin

### ISSUE THREAD

**Issue by jacobcrny** [Ganom/Supporter-Issue-Tracker#193]
**Describe the bug**
The plugin does not switch prayers at all in the fight even though they are off- ticked

**To Reproduce**
1. start a kill at Saradomin GWD
2.  plugin will not change prayers

**Expected behavior**
Should switch prayers against the minions while kiting the boss around the room

**Screenshots**

**Additional context**

**Comment by jacobcrny** [comment]
it tracks their attack tick correctly it just doesn't change prayer

**Comment by TranceHD** [comment]
I'm having the same issue at Arma. I'm wondering how widespread of an issue this is. I used Sara fine for 500+ kills perfectly. Now a few people are having issues w/ GWD
