### ISSUE TITLE
Hunter Helper - Salamanders stops working/pausing/crashing

### ISSUE THREAD

**Issue by Zezima42069** [Ganom/Supporter-Issue-Tracker#202]
The plugin works great but you literally can not touch anything on the client while it's running and/or move it/minimize it. If you open the side panel for any reason to see plugins or to see your exp/hr or maybe turn privacy on or off your character will just stand still and you will lose traps/log off from it not doing anything/stopping. This is the only plugin I've ever had this issue with. To get it back working correctly to re-trap etc you have to manually click 1-3 of the traps to either catch what you caught or to re-trap the tree and when you do that it will set them back up. It's like it stalls the plugin on a certain step and freaks it out. Very annoying to deal with at home or at work.

**Comment by Failed4life** [comment]
I've tested and verified the issue.
• Interacting with the client, whether it's toggling privacy mode, changing side bar tabs, closing/opening the side bar, etc, appears to break the Check Trap and Fallen Trap Looting functions of the plugin.
• Manually looting any fallen traps and checking any catches then toggling the plugin off/on causes the plugin to function correctly again
