### ISSUE TITLE
One Click or Left Click casting extensions.

### ISSUE THREAD

**Issue by Gittyhub123** [Ganom/Supporter-Issue-Tracker#204]
**Describe the solution you'd like**
New spells to One Click Spell Casting, or Left Click spellcasting. 

In particular, reanimation spells from the Arceuus spellbook. I suspect these will become vastly more popular with the release of the new spells in June.

In light of that, there will be new spells in June that it might be worth preparing for the release of, and adding some of these spells as well to the aforementioned plugins, but I'll get back to that when they're released and when we know exactly how they work.

**Describe alternatives you've considered**
No other option aside from manually clicking afaik.

**Comment by Failed4life** [comment]
This github is for the Premium plugins only. Also, it would be impossible to "prepare" for the release, as the entire spellbook is changing. Making changes a head of time would be wasted efforts
