### ISSUE TITLE
RC - Slave log out on MIA master

### ISSUE THREAD

**Issue by Blrugo** [Ganom/Supporter-Issue-Tracker#210]
**Is your feature request related to a problem? Please describe.**
To protect master at fire altar, log out helper is on so it can't be reported, but the slaves will stand there for 5 minutes 100% being reported if someone shows up. 

**Describe the solution you'd like**
Make it so if the slaves don't see the master at the altar they log out. 

**Describe alternatives you've considered**
The only other thing I could think of would be to add a setting to Log out helper that disables it at Castle Wars and Duel arena (where the slaves bank/run) so they only log out if someone unfamiliar is inside the fire altar. 

**Additional context**
This will help on ban rates, 6 of my slaves got banned. Before that I had seen twice in the slave player chat someone messaging "reported idiot", so I know they got reported.

**Comment by Ganom** [comment]
See #213
