### ISSUE TITLE
Combat Helper & Pick Pocket Helper: New Spell Functionality

### ISSUE THREAD

**Issue by GanomLover** [Ganom/Supporter-Issue-Tracker#212]
Is your feature request related to a problem? Please describe.
Neither feature requests are directly related to a problem with the existing code.

Describe the solution you'd like
Adding functionality for automated thralls while in combat would help across the board and could be implemented similarly to potion checks that already exist within the plugin. 

~~Adding functionality for the shadow veil spell while using the pick pocket helper could be implemented similarly to the dodgy necklace check that already exists within the plugin.~~

Describe alternatives you've considered

If these additions are not as straightforward to add to the listed plugins, perhaps there could be a new plugin that works alongside skilling/pvm for an automated thrall or any spell to be cast upon the spell timer ending.

**Comment by Failed4life** [comment]
Shadow Veil support was added to pphelper 👍

**Comment by Failed4life** [comment]
Combat Helper has Thrall support 👍
