### ISSUE TITLE
QoL RC/Logout Helper update

### ISSUE THREAD

**Issue by Krayeah** [Ganom/Supporter-Issue-Tracker#213]
**Is your feature request related to a problem? Please describe.**
When using RC Bot in conjunction with Logout Helper the master will obviously log out but the slaves loiter until the user frantically pauses RC Bot and manually logs all the slaves out, providing time for reports to go out. While slaves are meant to be disposable, they do represent actual money loss from sub time per ban.

**Describe the solution you'd like**
Very simply, when the error is thrown “cannot find master,” (occurs after entering altar and master not there) the slaves will log out. In a loop, that will make each slave log out as soon as they enter the altar after the master has logged out.

**Describe alternatives you've considered**
n/a

**Additional context**
So far no adverse affect to master, however I’ve lost 2.5 sets of slaves while babysitting on dead worlds and hopping if Castle Wars becomes congested. I believe a logout assist for slaves would have prevented some of that loss. Additional bonus of RC Bot (should someone want to risk it) becoming more afk. Can set up your run team not worry about checking it every 10s.

**Comment by Ganom** [comment]
Option to logout if master is not present has been added.
