### ISSUE TITLE
Humidify support for granite powermining

### ISSUE THREAD

**Issue by keenandotp** [Ganom/Supporter-Issue-Tracker#214]
Mining granite requires waterskins, which last for around 3 hours for a whole inventory. In order to stay here for longer periods of time, the player is either required to have a 99 HP cape + regen bracelet to 'out dps' the desert heat; desert amulet (DA) 4; use the humidify spell to fill waterskins; or bank for waterskins. It can get slightly tedious banking for waterskins and is sometimes a lengthy process. This may significantly reduce the player's time mining.

One way to circumvent the possibly tedious banking and not having the requirement for a DA/HP cape would be to make use of the Humidify spell. This would ensure that the player is able to stay at the quarry for as long as they like with the least amount of inputs as possible.

**Comment by Ganom** [comment]
I'm going to mark this won't fix as it encourages poor behavior. Doing any intense action like 3t4g should be monitored.
