### ISSUE TITLE
Combat helper- Food choices

### ISSUE THREAD

**Issue by rn1rnl** [Ganom/Supporter-Issue-Tracker#215]
**Is your feature request related to a problem? Please describe.**
The combat helper will eat any food in inventory, can we make it specify what to eat specifically by adding ID's? It's eating brews that I get from drops during pvm and I don't want it too.

**Describe the solution you'd like**
I'd like to be able to choose what foods to eat by item ID's

**Comment by ThatGamerBlue** [comment]
Added a config option to ignore certain food item ids.
