### ISSUE TITLE
RC Helper: Colossal pouch and ring of the elements support

### ISSUE THREAD

**Issue by kalaxd** [Ganom/Supporter-Issue-Tracker#239]
**Is your feature request related to a problem? Please describe.**
-

**Describe the solution you'd like**
Solo lava runes EHP got pushed way up due to the aforementioned new items

**Describe alternatives you've considered**
-

**Additional context**
Example video of current EHP:
https://www.youtube.com/watch?v=3ZKLpHjUxy4

**Comment by ThatGamerBlue** [comment]
Ring of the elements support has been added.

**Comment by Failed4life** [comment]
Colossal pouch is now supported in the open beta
