### ISSUE TITLE
Item dropper not working

### ISSUE THREAD

**Issue by abdallah0100** [Ganom/Supporter-Issue-Tracker#244]
**Describe the bug**
after the latest update, the item dropper plugin no longer works

**Comment by Failed4life** [comment]
This github is for issues and suggestions for the Premium plugin. Item Dropper is one of the free plugins, which has not been updated yet. We've made two announcements saying "The Free plugins are our last priority, they will be updated once the Platinum and Bronze plugins are fully back up and running"
