### ISSUE TITLE
One Click (Herb Option"

### ISSUE THREAD

**Issue by TranceHD** [Ganom/Supporter-Issue-Tracker#245]
**Describe the bug**
"One click" herb option isn't working anymore for composting troll stronghold, weiss, or Kourend patches for ultra compost. It does plant the seeds however. Just no option to compost it, just "inspect herbs". It worked a few days ago. Thanks :)

**To Reproduce**
Hovering over the herb patch does not give the option to one click use my ultracompost bucket on the 3 protected patches. It works fine for the other patches. It does let me plant the seed. 

**Expected behavior**
After clicking the herb patch and planting the seed, it should give the option to one click use compost on the herb patch. 

**Screenshots**

**Additional context**
Also, could you potentially add support to the farming guild herb patch? Thank you.  :)

**Comment by Failed4life** [comment]
This github is for the premium plugins, refer to free github for submitting issues with the free plugins.

Your issue however is likely due to you having the "Compost on protected" settings disabled.

**Comment by TranceHD** [comment]
I'm so sorry, I didn't see that option was added at the bottom. My mistake. This fixes the issue.
