### ISSUE TITLE
RCBot

### ISSUE THREAD

**Issue by monkas12345678** [Ganom/Supporter-Issue-Tracker#25]
**Describe the bug**
Bug 1) Sometimes banks earth runes. Happend to be 4 times in 25hours
Bug 2) When Leveling up in Castlewars doesn't go to the Bank itself
Bug 3) Gets stuck in NPC contact spell (Book of abyss in bank) just doesnt press spacebar?

**To Reproduce**

**Expected behavior**
To not bank Earth runes, move after level up text?, delay spacebar on npc contact spell

**Screenshots**

**Additional context**

**Comment by Ganom** [comment]
I'd prefer if you could make each bug into a separate issue.
