### ISSUE TITLE
Boss Swapper: Support for eagle eye and not just rigour for nylo

### ISSUE THREAD

**Issue by Rhino-RS** [Ganom/Supporter-Issue-Tracker#32]
**Is your feature request related to a problem? Please describe.**
the switcher only turns on rigour, and for ironmen like myself i don't have it, so If you could make it toggle eagle eye would be great
**Describe the solution you'd like**
Instead of trying to turn on rigour, make it so you can have it turn on eagle eye
**Describe alternatives you've considered**
Turning eagle eye on manually

**Comment by ThatGamerBlue** [comment]
misclicked the wrong issue oops
