### ISSUE TITLE
Banking Helper- Add support for different jewelry charges

### ISSUE THREAD

**Issue by Phillipluck** [Ganom/Supporter-Issue-Tracker#35]
**Is your feature request related to a problem? Please describe.**
Not related to a problem, would just be a quality of life update. Currently when using the banking helper to withdraw jewelry with charges, you need to have the exact ID associated to the charged item. For example ring of duellings have 8 different Item IDs. You either need to withdraw the ring manually each time, or change the item ID each time.

**Describe the solution you'd like**
Add logic to withdraw the lowest charged jewelry.
Or, maybe add some logic to withdraw the first found Item ID in a string. 
     "ie- w:2566,2564,2562,2560,2558,2556,2554,2552-1"
Those are the 8 Item IDs for the 8 charges of ring of duellings. Maybe once the string found one of those IDs in the bank, it would move on to the next line.

**Describe alternatives you've considered**
Withdrawing charged jewelry separately, or changing item ID's

**Additional context**
This update could work for charged jewelry, Barrows gear that degrades, teleport crystals

**Comment by Ganom** [comment]
Advanced swapper accepts strings, I can probably port that over to this plugin, so you'd type Ring of Dueling and it'd find the first one.

**Comment by Phillipluck** [comment]
> Advanced swapper accepts strings, I can probably port that over to this plugin, so you'd type Ring of Dueling and it'd find the first one.

Ganom, any idea when this might be implemented?
