### ISSUE TITLE
Custom Swapper: Keystrokes getting locked

### ISSUE THREAD

**Issue by kalaxd** [Ganom/Supporter-Issue-Tracker#36]
**Describe the bug**
Using custom swapper (at least on some hotkeys) will completely lock the user out from typing in-game. You can't type in chat or any menus that pop up.

**To Reproduce**
1. I've used "E" as a hotkey and managed to reproduce the issue with a 100% success rate.
2. Press the hotkey
3. You will not be able to type in-game

**Expected behavior**
Expect to be able to keep using the in-game typing features like normal.

**Screenshots**
-

**Additional context**
People have reported the same issue with different hotkeys.

**Comment by Ganom** [comment]
Are you sure this is related to the plugin?

**Comment by kalaxd** [comment]
The two plugins in use at that moment were item dropper and custom swapper. Item dropper alone has never resulted in the same happening.

**Comment by gaming875** [comment]
i can confirm it is this plugin, i had it happen quite often before upgradeing to plat, sometimes toggling the plugin off and then on again or  reset would fix it and allow me to type. and other times nothing but reloading a whole new client would stop the problem
