### ISSUE TITLE
Bankstand:Max Cape/Herblore Cape not supported

### ISSUE THREAD

**Issue by gaming875** [Ganom/Supporter-Issue-Tracker#37]
**Describe the bug**

**To Reproduce**

**Expected behavior**
When trying to mix up potions using max cape perk and grimy herbs, it will only a do a few then bank quickly and repeat, its caused because for some reason no animation is done while mixing potions using the cape perk. 
**Screenshots**

**Additional context**
It is nice for irons to not have to clean herbs or pay 200gp per potion, and although it does function as is i imagine its not ideal when manually reviewed for botting. Also having clean herbs option aswell in the same plugin, but asswell i imagine this is just better when it comes to ban detection side of things(instead of cleaning ten herbs per tick every tick)

**Comment by Failed4life** [comment]
Duplicate request
