### ISSUE TITLE
Bankstander: Prif anvil using wrong bank

### ISSUE THREAD

**Issue by DontJumper** [Ganom/Supporter-Issue-Tracker#41]
**Describe the bug**
When smithing in prif with bankstander the plugin will walk to the east bank instead of the middle one effectivly using more time and getting less xp/h

**To Reproduce**
1. Go to Prif
2. Enable bankstander and do 1 inv
3. Wait until you walk to the bank

**Expected behavior**
Walk/run to the middlebank 

**Screenshots**
https://streamable.com/r49jew

**Additional context**

**Comment by Ganom** [comment]
Aren't both paths exactly the same amount of tiles?

**Comment by DontJumper** [comment]
East bank is 1 more tile. In the Skilling discord they're getting 215k xp while walking to the middle bank and atm im getting 207k xp/h walking to east bank.
