### ISSUE TITLE
HunterHelper: Failed traps are only prioritized for salamanders.

### ISSUE THREAD

**Issue by Calmoran** [Ganom/Supporter-Issue-Tracker#42]
**Describe the bug**
plugin does not prioritize failed or laid down box traps when the option to prioritize them is ticked on.

**To Reproduce**
turn on grab failures first
start plugin
let it do its thing. eventually it will have a failed one and if there are successfully trapped chins it doesn't prioritize them

**Expected behavior**
I'm assuming expected behavior is to grab the failed/laid down box traps first before successful ones

**Screenshots**
https://i.imgur.com/1HURhLl.png
https://i.imgur.com/BPIvauy.png
https://i.imgur.com/wN9WFuw.png
https://i.imgur.com/le5GOAG.png
https://i.imgur.com/5jiHTX0.png
https://i.imgur.com/bxT0DNX.png

these screenshots are in order from top to bottom of what boxes it chose to open

**Additional context**

**Comment by Ganom** [comment]
This option is only for salamanders currently.

**Comment by Failed4life** [comment]
Option has been applied to Chins as well
