### ISSUE TITLE
Log-Out Helper Teleport Request

### ISSUE THREAD

**Issue by Jordh1337** [Ganom/Supporter-Issue-Tracker#47]
**Is your feature request related to a problem? Please describe.** I
No.

**Describe the solution you'd like**
Instead of logging you out instantly teleports you out with multiple option eg Varrock teleport, Royal seed pod etc.

**Describe alternatives you've considered**

**Additional context**
It would be handy for people under 20/30 wilderness where if somebody could attack you it would instantly teleport you out as you could be in combat in multi area.

**Comment by Failed4life** [comment]
Support for Glory and Royal Seed Pod has been added
