### ISSUE TITLE
More teleport options for log-out-bot

### ISSUE THREAD

**Issue by ZZNQX** [Ganom/Supporter-Issue-Tracker#51]
**Is your feature request related to a problem? Please describe.**
Currently you added support for the glory & royal seed pod, but there are a handful of other teleports that do the same thing and it would be very useful if we these can be supported.

**Describe the solution you'd like**
There are a total of 9 teleportation methods that support teleportation up to level 30 that I would love to see added, prioritised in a list from most important to least important.

### Level 30
- [x] Ring of wealth & its imbued version
- [x] Amulet of glory & its trimmed versio
- [x] Slayer Ring
- [x] Combat bracelet
- [x] Royal seed pod
- [x] Skills Necklace
- [x] Amulet of eternal glory
### Level 20
- [x] Ectophial
- [x] Ring of duelling
- [ ] Spellbook based teleports/tablets

**Describe alternatives you've considered**

**Additional context**
Alternatively it would be cool if we could pick our teleport option like on advanced swapper. Maybe its possible to use the same logic advanced swapper uses for this for example: e:Amulet of glory:2 (for edgeville)

**Comment by Ganom** [comment]
> Pharaoh's scepter

:pepelaughpoint: at anyone who brings that into the wildy. Other than looks fine.

**Comment by Ganom** [comment]
> Spellbook based teleports/tablets

Not sure if i'm going to add support for these unless i can think of a way to do it without manually adding EVERY SINGLE teleport.

**Comment by ZZNQX** [comment]
> 
> 
> > Spellbook based teleports/tablets
> 
> Not sure if i'm going to add support for these unless i can think of a way to do it without manually adding EVERY SINGLE teleport.

Yeah this is really not necessairy, it wouldnt be a very much used option.
