### ISSUE TITLE
PowerGatherer: Sandstone Grinding Support

### ISSUE THREAD

**Issue by kurryboi** [Ganom/Supporter-Issue-Tracker#6]
Hi Ganom,

I was wondering if you could add an extension to the mining plugin. Instead of dropping sandstone, could you create something that would click the grinder and then return back to mining? There is currently a work around by selecting woodcutting and manually clicking once every time the inventory is full, but I would appreciate it if you could make this process fully automated. Thanks so much for your hard work. Your plugins have been amazing!

**Comment by Ganom** [comment]
This is something I'd like to do, but it'd require a decent amount of work, as such it'll be a bit lower on the priority.

**Comment by rmwyatt** [comment]
I would be interested in financially commissioning this depending on how much it would cost?

**Comment by ThatGamerBlue** [comment]
This is finally done 😎
