### ISSUE TITLE
RC No Multiple Talismans

### ISSUE THREAD

**Issue by c-madoc** [Ganom/Supporter-Issue-Tracker#60]
**Describe the bug**
Setting talisman amount to 1 works
Setting talisman amount to 2 doesn't work.
When the bot goes to withdraw supplies, it doesn't take any talismans out, withdraws ess, and then teleports.

**To Reproduce**

1. Go to RC Bot

2. Set Main Config to:
- Lavas
- Pure Essence

2. Set Bot Config to:
- Magic imbue: OFF
- Bring Talisman: ON
- Talisman Quant: 2

3. Start script.

**Expected behavior**
Withdraw expected amount of talismans

**Comment by c-madoc** [comment]
I found that the fix is to set to "Withdraw-X" and set the amount to "2".

**Comment by Ganom** [comment]
Fixed with release 1.2.0
