### ISSUE TITLE
Hunleff Helper is not praying correctly

### ISSUE THREAD

**Issue by herewegothen** [Ganom/Supporter-Issue-Tracker#64]
**Describe the bug**
Upon entering the Hunleff room the plugin begins to 1 tick flick mage and doesn't allow the player to do anything else.  It has happened my last two runs, but doesn't always happen.

**To Reproduce**
1. Enter into hunleff room.
2.  First started to happen when I got stomped by Hunleff when entering the room.

**Expected behavior**
I expected the plugin to not one tick flick mage prayer, but to use the appropriate prayers to prevent most damage from hunleff.

**Screenshots**

**Additional context**

**Comment by Ganom** [comment]
Thats the first i'm hearing of this issue, did you follow the troubleshooting guide in the faq?

**Comment by herewegothen** [comment]
I did that and just had the error again.  I can send you the logs if you'd like.
