### ISSUE TITLE
Auto-Eater

### ISSUE THREAD

**Issue by connr** [Ganom/Supporter-Issue-Tracker#68]
**Is your feature request related to a problem? Please describe.**

The problem is that I have to click my screen manually o digest fish, or search for another plugin that isn’t as good.

**Describe the solution you'd like**
An ability to choose multiple options to eat when below a certain HP. An option to input which ID to eat as well as option to tick eat to increase health.

**Describe alternatives you've considered**
Paying another developer or free plugins (which are garbage)

**Additional context**
Please.

**Comment by Ganom** [comment]
Technically you can use agility helper for auto eat, but the issue tracker is not for plugin requests.

**Comment by connr** [comment]
Where can we do requests?
