### ISSUE TITLE
AdvanceSwapper: Dead clicks after emptying pouches

### ISSUE THREAD

**Issue by DontJumper** [Ganom/Supporter-Issue-Tracker#7]
**Describe the bug**
After emptying RC pouches it will not register clicks anymore unless you move your mouse 
It will also do this with empty pouches 

**To Reproduce**
1. Go to advanced swapper 
2. Make 2 swaps  (Giant, large e:5514 e:5512) ( Small, medium e:5510 e:5509
3. Put pouches in your inv and empty them with your hotkey 

**Expected behavior**
I expected it to make me able to click without moving my mouse

**Screenshots**
When you see the name on the top left disappear ive just pressed the hotkey and im spamming the mouse
https://streamable.com/3b09ip

**Additional context**
Nothing more to add

**Comment by DontJumper** [comment]
After trying out some of the other methods like equipping, eating, teleporting i can safely say its not a problem only with rc pouches as the bug still persists

**Comment by Ganom** [comment]
> 
> 
> After trying out some of the other methods like equipping, eating, teleporting i can safely say its not a problem only with rc pouches as the bug still persists

Are the dead clicks actually dead (as in do nothing), or dead as in the cross sprite doesn't appear?

**Comment by DontJumper** [comment]
> 
> 
> > After trying out some of the other methods like equipping, eating, teleporting i can safely say its not a problem only with rc pouches as the bug still persists
> 
> Are the dead clicks actually dead (as in do nothing), or dead as in the cross sprite doesn't appear?

Both, Clicks does not register and sprite does not show up

**Comment by Ganom** [comment]
Unable to reproduce this issue on a clean environment.

I'm curious as to why this is happening for you, I assume this is also related to the previous issue you contacted me about. Are you using the launcher version of OpenOSRS?

**Comment by DontJumper** [comment]
Thats sad to hear.
I actually dont know if this is related to the rc problem but it might be? Yes im using the launcher version.
