### ISSUE TITLE
Log-out-bot Area Mapping

### ISSUE THREAD

**Issue by not-tivia** [Ganom/Supporter-Issue-Tracker#70]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Allow users the option to use [Explv's map](https://explv.github.io/) to define the area they want to check for other players in, often times accounts get logged out because a noob/bot far in the distance walking by.

This would allow you to create an area around, for example the runecrafting alter, a chinchompa hunting area, or an area around a random bank you are skilling at.

**Describe alternatives you've considered**
Could just have a slider that you can adjust to check for players within x range, so if I run by someone and they are within 8 tiles of me i Instalog

**Additional context**

**Comment by Ganom** [comment]
Too niche of a use case imo.
