### ISSUE TITLE
Increasing limit for delays

### ISSUE THREAD

**Issue by gaymer234** [Ganom/Supporter-Issue-Tracker#73]
**Is your feature request related to a problem? Please describe.**
Sometimes the clicks seem too tick perfect

**Describe the solution you'd like**
Allow us to configure the delay up to 10 seconds except for 3t.

**Describe alternatives you've considered**
Used the delay on the Updater, doesn't feel long enough

**Additional context**

**Comment by Ganom** [comment]
Delays are reaction delays, not logic delays, as such this will not be possible.
