### ISSUE TITLE
PowerGatherer: Support for Infernal Eel & Sacred Eel support

### ISSUE THREAD

**Issue by Zereull** [Ganom/Supporter-Issue-Tracker#74]
**Is your feature request related to a problem? Please describe.**
Safer alternative then 3tick barb fishing.

**Describe the solution you'd like**
Fish an inventory full of eels and then cut/smash them with the knife/hammer

**Describe alternatives you've considered**
Barb fishing?

**Additional context**
https://oldschool.runescape.wiki/w/Money_making_guide/Catching_infernal_eels

https://oldschool.runescape.wiki/w/Money_making_guide/Catching_sacred_eels

**Comment by Failed4life** [comment]
Sacred Eels are already supported, put the fish id into the "Items to Cut" field and have a knife in your inventory

Edit: I cannot remember if Infernal Eels were added as well
