### ISSUE TITLE
Change to One Click to work with Power Gatherer

### ISSUE THREAD

**Issue by nutwick** [Ganom/Supporter-Issue-Tracker#78]
**Is your feature request related to a problem? Please describe.**

When Power Gatherer is on along with One Click at tithe farm, "Mark for Gather" is prioritized in the menu entry and "Use seed ->tithe patch" is no longer an option. Plants at tithe farm are able to be marked for power gatherer and it carries out the minigame until the plants are ready to harvest when using the "Stalls" option. It will not harvest the plants despite being marked for gatherer. 

**Describe the solution you'd like**

Possibly exclude menu actions in One Click that contain "Mark" to fix the issue with Power Gatherer. Add support in Power Gatherer to mark tithe patch tiles so it can "One Click" those tiles for the initial planting. Add support for harvesting plants after they have grown when marked by Power Gatherer (no idea why it doesn't currently work)

**Describe alternatives you've considered**

Add feature in Power Gatherer to use an item ID (like seed) on sequentially marked tithe patch tiles for initial planting. 

**Additional context**

This solution would not provide maximum efficiency in the minigame because it would not prioritize the plants that are closest to dying to be watered. You would only be able to plant 8-10 seeds at a time, but it would make the minigame much more afk.

**Comment by Failed4life** [comment]
Power Gatherer is not intended to be used for Tithe Farm, sounds like you're trying to make a ghetto work-a-round.

It would likely be an easier task for Ganom to make a Tithe Farm plugin if he chose to do so.
