### ISSUE TITLE
Boss Swapper: crashing at Olm 2nd phase

### ISSUE THREAD

**Issue by absyer** [Ganom/Supporter-Issue-Tracker#79]
**Describe the bug**
My client freezes up and must be closed at certain points during the Olm 2nd phase. Usually when trying to re-apply prayers after being hit by lightning or when I manually eat brews.
[client.log](https://github.com/Ganom/Supporter-Issue-Tracker/files/5198200/client.log)

**To Reproduce**
1. Go to Boss Swapper
2. Do Olm

**Expected behavior**
No crashing/freezing

**Screenshots**

**Additional context**
I had Anti-Drag enabled and suspect that might be an issue. Just crashed 3 times in a row and don't have time atm to try another Olm to see if i crash again.

**Comment by Ganom** [comment]
You have legacy plugins that are causing the crashes, follow the FAQ to resolve this issue.
