### ISSUE TITLE
AdvBossSwapper: Demonic Gorillas

### ISSUE THREAD

**Issue by Jordh1337** [Ganom/Supporter-Issue-Tracker#8]
**Describe the bug**

**To Reproduce**
1. Go to Demonic Gorillas with adv boss swapper enabled.
2. Once ready to bank go to bank and resupply
3. Go back and it stops working correctly doesn't change prayers or gear.

**Expected behavior**
Expected to go back to demonics after resupplying and being able to continue but doesn't change prayers or gear.

**Comment by Shieldeh** [comment]
https://pastebin.com/aRJsahM1

Had this happen while doing demonics, here's the error from Client.log
