### ISSUE TITLE
GE Logburner

### ISSUE THREAD

**Issue by kylerodgers1994** [Ganom/Supporter-Issue-Tracker#82]
Firemaking Feature.

a simple script that burns logs in the grand exchange, this is a good method of training firemaking even with one click enabled. Can see very good XP rates and is handy for early game for wintertotd or even max efficiency to max.

Logs to range from regular - redwoods. I'm not 100% sure how people manage over 600k xp hour but i did over 350-400k manually.

**Comment by Phillipluck** [comment]
This will likely get ignored. Github is for bug reports, not script requests.
