### ISSUE TITLE
Power Gather Mining pattern

### ISSUE THREAD

**Issue by Mattjones171** [Ganom/Supporter-Issue-Tracker#84]
I noticed whenever using Power Gather, it may skip a rock sometimes causing the rhythm to go out of order when 3 ticking granite for example

Place a check that makes sure the rock that it is closest to is being depleted before continuing to the next, place a sequence order that the mining pattern takes (when making rocks it should always go in the order they are marked)

I've tried a few things like swapping the tick manip off and it will always go in order, but when it's on it will skip rocks

[Image](http://texas.gg/img/OpenOSRS_tTzVfEKb0z.png)

**Comment by Ganom** [comment]
> I noticed whenever using Power Gather, it may skip a rock sometimes causing the rhythm to go out of order when 3 ticking granite for example
> 
> Place a check that makes sure the rock that it is closest to is being depleted before continuing to the next, place a sequence order that the mining pattern takes (when making rocks it should always go in the order they are marked)
> 
> I've tried a few things like swapping the tick manip off and it will always go in order, but when it's on it will skip rocks
> 
> [Image](http://texas.gg/img/OpenOSRS_tTzVfEKb0z.png)

Doing that breaks rhythm and is not recommended.
