### ISSUE TITLE
Pickpocket Helper: H.A.M. Member pickpocket isn't working

### ISSUE THREAD

**Issue by Lorenso0** [Ganom/Supporter-Issue-Tracker#92]
**Describe the bug**
When you target a H.A.M. Member and start the plugin it'll display the state as "thieving" but it's not actually pickpocketing the member, the "walk here" option in the top left corner does keep appearing and disappearing, so it is doing someting

**To Reproduce**
1. Go to the H.A.M. hideout
2. Right click target a H.A.M. Member
3. Start the plugin
4. See the state change to "Thieving" but notice the pickpocketing not actually happening

**Expected behavior**
I expect the plugin to pickpocket the H.A.M. Members for easy clues

**Screenshots**
https://imgur.com/2ePgau7
Well, screenshot doesn't really show anything but I think you get the issue 😅

**Comment by Ganom** [comment]
This is because its technically not pickpocket, but a separate action. I can add this.
