### ISSUE TITLE
PPHelper: eat while stunned

### ISSUE THREAD

**Issue by endear834** [Ganom/Supporter-Issue-Tracker#96]
**Is your feature request related to a problem? Please describe.**

At a low HP, doing blackjacking can result in multiple deaths. The script will continue to try and knockout regardless of HP and will suicide
**Describe the solution you'd like**
Eat regardless of action if HP hits certain value versus eating only when NPC is knocked out

**Describe alternatives you've considered**
n/a
**Additional context**
n/a

**Comment by Ganom** [comment]
Eating regardless of action WILL result in death, as that will put you in combat.
